### ISSUE TITLE
Fix en logaritmos de una división

### ISSUE THREAD

**Issue by jbkunst** [GaboCg/talks#1]
Hola!

Si no me equivoco 😅 , en:

https://github.com/GaboCg/talks/blob/e848d23940686d324d58776c30b5bac28906b22d/xaringan/enmec_t3/index.Rmd#L258

Debe ser:

$$r_t = \log(1 + R_t) = \log(\frac{P_t}{P_{t-1}}) = \log(p_t) - \log(p_{t-1})$$

![image](https://user-images.githubusercontent.com/56481/56098801-6c9ecb80-5ed2-11e9-856e-0f7dd2d62b70.png)

**Comment by gabbocg** [comment]
Hola,

La verdad es que $p_t$ = $ \log(P_t)$ y $p_{t-1}$ = $\log(P_{t-1})$, gracias por la sugerencia, debido que puede llevar a confusión. Ahora que estoy ordenando algunas presentación lo agregaré.

Arigato

**Comment by jbkunst** [comment]
Verdad! Me equivoqué con las mayúsculas y minúsculas. Tienes toda la razón. Disculpe!
